modLoader = "javafml"
loaderVersion = "[47,)"
license = "CC0-1.0"

[[mods]]
modId = "nightfalloverlay"
version = "${version}"
displayName = "NightFallOverlay"
authors = "Kendo and Nightfall team"
logoFile = "icon.png"
description = '''
Custom nickname overlay for Plasmo Voice, with real-time tab-list and chat renaming.
'''

[[dependencies.nightfalloverlay]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nightfalloverlay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nightfalloverlay]]
modId = "plasmovoice"
mandatory = false
versionRange = "[2.0,)"
ordering = "AFTER"
side = "SERVER"
